### ISSUE TITLE
Usage of non existing "Get Expense Accounts" shortcut within the "Add Transaction" shortcut

### ISSUE THREAD

**Issue by rheggen** [dimarei/firelfy-ios-shortcuts#1]
Just wanted to inform you: the "Add Transaction" shortcut has a bug when accessing the "Get Accounts" shortcut while entering an expense. It tries to use the "Get Expense Accounts" shortcut, which does not exist. If you change this to the "Get Accounts" shortcut everything is working fine.

**Comment by dtrainych** [comment]
> Just wanted to inform you: the "Add Transaction" shortcut has a bug when accessing the "Get Accounts" shortcut while entering an expense. It tries to use the "Get Expense Accounts" shortcut, which does not exist. If you change this to the "Get Accounts" shortcut everything is working fine.

Thank you so much, I fixed it!
