### ISSUE TITLE
Only some destination accounts shown

### ISSUE THREAD

**Issue by klejejs** [dimarei/firelfy-ios-shortcuts#3]
Currently when creating a withdrawal, only first part of destination accounts are shown. For me it seems names up-to letter that starts with "e".

**Comment by dtrainych** [comment]
Hi @klejejs
Can you tell how many expense accounts do you have in Firefly III? 
API method /api/v1/accounts returns first 50 accounts, so maybe the problem is that you have more that 50 expense accounts.

**Comment by klejejs** [comment]
Hey, I have over 150 of them. Is there a way to show them all or somehow filter them with search?

**Comment by ClemABT** [comment]
Same issue here, only the first page of the destination accounts for a withdrawal are shown.

**Comment by dtrainych** [comment]
Hi @klejejs @ClemABT,
I modified the shortcut to get all accounts if there are more than 50. Please re-import the "List accounts" shortcut and test it, thank you.

**Comment by ClemABT** [comment]
All good for me, it’s working now.
Thanks.

**Comment by klejejs** [comment]
Great, thank you! Scrolling is a bit laggy now, but I guess that's how iOS works.
